// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Login                string   `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Avatar               string   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserByCreate struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserByCreate) Reset()         { *m = UserByCreate{} }
func (m *UserByCreate) String() string { return proto.CompactTextString(m) }
func (*UserByCreate) ProtoMessage()    {}
func (*UserByCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserByCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserByCreate.Unmarshal(m, b)
}
func (m *UserByCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserByCreate.Marshal(b, m, deterministic)
}
func (m *UserByCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserByCreate.Merge(m, src)
}
func (m *UserByCreate) XXX_Size() int {
	return xxx_messageInfo_UserByCreate.Size(m)
}
func (m *UserByCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_UserByCreate.DiscardUnknown(m)
}

var xxx_messageInfo_UserByCreate proto.InternalMessageInfo

func (m *UserByCreate) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *UserByCreate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserByCreate) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UpdateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserRequest struct {
	User                 *UserByCreate `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUser() *UserByCreate {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetUserByLoginResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByLoginResponse) Reset()         { *m = GetUserByLoginResponse{} }
func (m *GetUserByLoginResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserByLoginResponse) ProtoMessage()    {}
func (*GetUserByLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *GetUserByLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByLoginResponse.Unmarshal(m, b)
}
func (m *GetUserByLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByLoginResponse.Marshal(b, m, deterministic)
}
func (m *GetUserByLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByLoginResponse.Merge(m, src)
}
func (m *GetUserByLoginResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserByLoginResponse.Size(m)
}
func (m *GetUserByLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByLoginResponse proto.InternalMessageInfo

func (m *GetUserByLoginResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetUserByLoginRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByLoginRequest) Reset()         { *m = GetUserByLoginRequest{} }
func (m *GetUserByLoginRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserByLoginRequest) ProtoMessage()    {}
func (*GetUserByLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *GetUserByLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByLoginRequest.Unmarshal(m, b)
}
func (m *GetUserByLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByLoginRequest.Marshal(b, m, deterministic)
}
func (m *GetUserByLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByLoginRequest.Merge(m, src)
}
func (m *GetUserByLoginRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserByLoginRequest.Size(m)
}
func (m *GetUserByLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByLoginRequest proto.InternalMessageInfo

func (m *GetUserByLoginRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

type GetUserByIdResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByIdResponse) Reset()         { *m = GetUserByIdResponse{} }
func (m *GetUserByIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserByIdResponse) ProtoMessage()    {}
func (*GetUserByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *GetUserByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByIdResponse.Unmarshal(m, b)
}
func (m *GetUserByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByIdResponse.Marshal(b, m, deterministic)
}
func (m *GetUserByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByIdResponse.Merge(m, src)
}
func (m *GetUserByIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserByIdResponse.Size(m)
}
func (m *GetUserByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByIdResponse proto.InternalMessageInfo

func (m *GetUserByIdResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetUserByIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByIdRequest) Reset()         { *m = GetUserByIdRequest{} }
func (m *GetUserByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserByIdRequest) ProtoMessage()    {}
func (*GetUserByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *GetUserByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByIdRequest.Unmarshal(m, b)
}
func (m *GetUserByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByIdRequest.Marshal(b, m, deterministic)
}
func (m *GetUserByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByIdRequest.Merge(m, src)
}
func (m *GetUserByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserByIdRequest.Size(m)
}
func (m *GetUserByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByIdRequest proto.InternalMessageInfo

func (m *GetUserByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*UserByCreate)(nil), "user.UserByCreate")
	proto.RegisterType((*UpdateUserRequest)(nil), "user.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "user.UpdateUserResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "user.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "user.CreateUserResponse")
	proto.RegisterType((*GetUserByLoginResponse)(nil), "user.GetUserByLoginResponse")
	proto.RegisterType((*GetUserByLoginRequest)(nil), "user.GetUserByLoginRequest")
	proto.RegisterType((*GetUserByIdResponse)(nil), "user.GetUserByIdResponse")
	proto.RegisterType((*GetUserByIdRequest)(nil), "user.GetUserByIdRequest")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x4b, 0x33, 0x31,
	0x10, 0xa6, 0xdb, 0x6d, 0xdf, 0xb7, 0x53, 0x29, 0x74, 0xd4, 0x1a, 0x57, 0x11, 0x29, 0x22, 0x5e,
	0xac, 0xd0, 0x2a, 0x08, 0x1e, 0x84, 0x7a, 0x10, 0xd1, 0x53, 0xb5, 0x17, 0x6f, 0xd1, 0x1d, 0xca,
	0xa2, 0x76, 0xd7, 0x24, 0xad, 0xf8, 0x6f, 0xfc, 0xa9, 0xb2, 0x49, 0xdb, 0xa4, 0xbb, 0x0b, 0xee,
	0x2d, 0xf3, 0xf1, 0x7c, 0x64, 0x32, 0x01, 0x98, 0x49, 0x12, 0xbd, 0x44, 0xc4, 0x2a, 0x46, 0x3f,
	0x3d, 0x77, 0x15, 0xf8, 0x63, 0x49, 0x02, 0x5b, 0xe0, 0x45, 0x21, 0xab, 0x1c, 0x56, 0x4e, 0x1a,
	0x23, 0x2f, 0x0a, 0x71, 0x0b, 0x6a, 0xef, 0xf1, 0x24, 0x9a, 0x32, 0x4f, 0xa7, 0x4c, 0x80, 0x08,
	0xfe, 0x94, 0x7f, 0x10, 0xab, 0xea, 0xa4, 0x3e, 0x63, 0x07, 0xea, 0x7c, 0xce, 0x15, 0x17, 0xcc,
	0xd7, 0xd9, 0x45, 0x84, 0x01, 0xfc, 0x4f, 0xb8, 0x94, 0x5f, 0xb1, 0x08, 0x59, 0x4d, 0x57, 0x56,
	0x71, 0xf7, 0x09, 0x36, 0x52, 0xd5, 0xe1, 0xf7, 0x8d, 0x20, 0xae, 0xc8, 0xaa, 0x55, 0x8a, 0xd4,
	0x3c, 0x47, 0xcd, 0x65, 0xad, 0x66, 0x58, 0x07, 0xd0, 0x1e, 0x27, 0x21, 0x57, 0x94, 0x72, 0x8f,
	0xe8, 0x73, 0x46, 0x52, 0xe1, 0x01, 0xe8, 0x8b, 0x6a, 0xe6, 0x66, 0x1f, 0x7a, 0x7a, 0x02, 0xba,
	0xc1, 0x0c, 0xe0, 0x1c, 0xd0, 0x05, 0xc9, 0x24, 0x9e, 0x4a, 0xfa, 0x13, 0x75, 0x05, 0x6d, 0x63,
	0xdd, 0x95, 0x3a, 0x5e, 0x03, 0xa1, 0x05, 0x2d, 0xef, 0x69, 0x25, 0x5d, 0x70, 0x49, 0xc9, 0x4b,
	0xe8, 0xdc, 0x92, 0x32, 0x74, 0x0f, 0xe9, 0x7c, 0x4a, 0x23, 0x4f, 0x61, 0x3b, 0x8b, 0x34, 0x86,
	0x0b, 0xc7, 0xde, 0xbd, 0x80, 0xcd, 0x55, 0xfb, 0x5d, 0x58, 0x5a, 0xe5, 0x08, 0x70, 0x0d, 0x66,
	0x24, 0x32, 0x7b, 0xd5, 0xff, 0xf1, 0xa0, 0x99, 0xf6, 0x3c, 0x92, 0x98, 0x47, 0xaf, 0x84, 0xf7,
	0xd0, 0x5a, 0xf7, 0x86, 0x7b, 0x86, 0xb9, 0xd0, 0x71, 0xb0, 0x5f, 0x5c, 0x5c, 0x58, 0x1c, 0x42,
	0xd3, 0xb1, 0x80, 0x2c, 0xd3, 0xbc, 0x72, 0x15, 0xec, 0x16, 0x54, 0x16, 0x1c, 0xd7, 0x00, 0xf6,
	0x71, 0x70, 0xc7, 0x34, 0xe6, 0xde, 0x3a, 0x60, 0xf9, 0x82, 0x25, 0xb0, 0x0b, 0xb5, 0x24, 0xc8,
	0xed, 0xe5, 0x92, 0x20, 0xbf, 0x7b, 0xc3, 0xc6, 0xf3, 0xbf, 0xe4, 0x6d, 0x72, 0xc6, 0x93, 0xe8,
	0xa5, 0xae, 0xbf, 0xea, 0xe0, 0x37, 0x00, 0x00, 0xff, 0xff, 0xff, 0x73, 0x34, 0x7b, 0xb8, 0x03,
	0x00, 0x00,
}
